project/club/urls.py
from django.urls import path
from . import views


app_name = 'club'
urlpatterns = [
    path('', views.club, name='club_portal'),  # route for the club space
    path('form/', views.submit_event_view, name='submit_event'), # the submittion of the event request and route to form page
    path('form/<pk>', views.form_view, name='view')
]

project/main/urls.py
from django.urls import path
from . import views


app_name = 'main'
urlpatterns = [
    path('', views.index_view, name='index'), # route for the authentication page
    path('signup/', views.signup_view, name='signup'),#route for sign up page
    path('login/', views.login_view, name='login'), # route for login
    path('logout/', views.logout_view, name='logout'), # route for logout
]

project/project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Club/', include("club.urls")),
    path('Administration/', include('administration.urls')),
    path('main/', include('main.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/club/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.
class Request (models.Model):
    status = (
        ('await', 'Await'),
        ('process', 'Accepted'),
        ('denied', 'Denied'),
    )
  
    statut = models.CharField(max_length=10, choices=status, default='await')
    name = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.CharField(max_length=50, blank=False, null=False)
    classe = models.CharField(max_length=5, blank=False, null=False)
    date = models.DateTimeField(blank=False, null=False,default=timezone.now()  )
    description = models.TextField()
    note = models.TextField(blank=True, null=True)
    date_request =models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{ self.name.username } request"

project/templates/index.html
<!DOCTYPE html>

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        {% block stylesheet %}
        {% endblock %}
    </head>
    <body>
        {% block content %}
        {% endblock %}


        {% block js %}
        {% endblock %}
    </body>
</html>

project/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
   

    <!-- Title Page-->
    <title>{{ user.username|title }} </title>

    <link href="{% static '/club/css/font-face.css' %}" rel="stylesheet" media="all">
    <link href="{% static '/club/vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet"
        media="all">
    <link href="{% static '/club/vendor/bootstrap-4.1/bootstrap.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static '/club/css/theme.css' %}" rel="stylesheet" media="all">
    {% block stylesheet %}
    {% endblock %}
</head>

<body>
{% if user.is_authenticated   %}
    <header class="header-desktop4">
        <div class="container">
            <div class="header4-wrap">
                <div class="header__logo">
                    <a href="{% url 'main:index' %}">
                        <h1 class="text-dark">ISI EVENTS </h1>
                    </a>
                </div>
                <div class="header__tool">
                    <div class="header-button-item {{ notification }} js-item-menu">
                        <!-- just delete has-noti -->
                        <i class="zmdi zmdi-notifications"></i>
                        {% if notification  and  user.is_staff %}
                        <div class="notifi-dropdown js-dropdown">
                            <div class="notifi__title">
                                <p>Pending Notifications </p>
                            </div>
                            <div class="notifi__item">
                                <div class="bg-c3 img-cir img-40">
                                    <i class="zmdi zmdi-file-text"></i>
                                </div>
                                <div class="content">
                                    <p>You have pending request </p>
                                </div>
                            </div>
                            <div class="notifi__footer">
                                <a href="{% url 'main:index' %}">Scroll down to see the full list</a>
                            </div>
                        </div>
                        {% elif notification and not user.is_staff   %}
                        <div class="notifi-dropdown js-dropdown">
                            <div class="notifi__title">
                                <p>Pending Notifications </p>
                            </div>
                        {% for request in requests_not_await %}
                            <a class="notifi__item" href="{% url 'main:index' %}">
                                <div class="bg-c3 img-cir img-40">
                                    <i class="zmdi zmdi-file-text"></i>
                                </div>
                                <div class="content">
                                   
                                    <p>{{ request.event }} :   {{ request.get_statut_display  }}</p>
                                    
                                    <span>{{ request.note }}</span>
                                    
                                </div>
                            </a>
                        {% endfor %}    
                            <div class="notifi__footer">
                                <a  href="" >Delete Notifications</a>
                            </div>
                        </div>

                        {% else %}
                        <div class="notifi-dropdown js-dropdown">
                            <div class="notifi__title">
                                <p> No Notifications</p>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                    <div class="account-wrap">
                        <div class="account-item account-item--style2 clearfix js-item-menu">
                            <div class="image">
                                <img src=" /{{ user.profile.image.url }}" alt="" />
                            </div>

                            <div class="content">
                                <a class="js-acc-btn" href="#">&nbsp;{{ user.username|title }}  &nbsp;</a>
                            </div>
                            
                                
                        
                            <div class="account-dropdown js-dropdown">
                                <div class="info clearfix">
                                    <div class="image">
                                        <a href="#">
                                            <img src="/{{ user.profile.image.url }}" alt="{{ user.username|title }}" />
                                        </a>
                                    </div>
                                    <div class="content">
                                        <h5 class="name">
                                            <a href="#">{{ user.username|title }}</a>
                                        </h5>
                                        <form method="POST", action="" , enctype="multipart/form-data">
                                            {% csrf_token %}
                                        <p class="file-upload" >
                                            {{ form }}
                                            <button type="submit" class="btn btn-dark">save</button>
                                        </p>
                                    </form>
                                    </div>
                                </div>
                               
                                <div class="account-dropdown__footer">
                                    <a href="{% url 'main:logout' %}">
                                        <i class="zmdi zmdi-power"></i>Logout</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- END HEADER DESKTOP -->

    <!-- WELCOME-->
    <section class="welcome2 p-t-20 p-b-20">
        <div class="container">

            <div class="row">
                <div class="col-md-10">
                    <div class="welcome2-inner m-t-2">
                        <div class="welcome2-greeting">
                            <h1 class="title-6">Hi
                                <span>{{ user.username|title }}</span>, Welcome back</h1>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- END WELCOME-->

    {% block content %}
    {% endblock %}



    {% else %}
    <p>You are not logged in</p>
    <a href="{% url 'main:index' %}">login from here</a>
    {% endif %}


    <script src="{% static '/club/vendor/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static '/club/vendor/chartjs/Chart.bundle.min.js' %}"></script>
    <script src="{% static '/club/vendor/animsition/animsition.min.js' %}"></script>
    <script src="{% static '/club/js/main.js' %}"></script>

{% block js%}
{% endblock %}

</body>

</html>
<!-- end document-->