project/administration/urls.py
from django.urls import path
from . import views



app_name = 'administration'
urlpatterns = [
    path('', views.admin, name='admin_portal'), 
    path('request/<pk>/', views.request_view, name='request_form'),
    path('request/<pk>/submit/', views.submit_view, name='submit_form'),
]

project/club/urls.py
from django.urls import path
from . import views


app_name = 'club'
urlpatterns = [
    path('', views.club, name='club_portal'),  # route for the club space
    path('form/', views.submit_event_view, name='submit_event'), # the submittion of the event request and route to form page
    path('form/<pk>', views.form_view, name='view')
]

project/project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Club/', include("club.urls")),
    path('Administration/', include('administration.urls')),
    path('main/', include('main.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/club/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.
class Request (models.Model):
    status = (
        ('await', 'Await'),
        ('process', 'Accepted'),
        ('denied', 'Denied'),
    )
  
    statut = models.CharField(max_length=10, choices=status, default='await')
    name = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.CharField(max_length=50, blank=False, null=False)
    classe = models.CharField(max_length=5, blank=False, null=False)
    date = models.DateTimeField(blank=False, null=False,default=timezone.now()  )
    description = models.TextField()
    note = models.TextField(blank=True, null=True)
    date_request =models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{ self.name.username } request"

project/club/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render
from django.urls import reverse
from main.forms import ProfileForm
from .models import Request
from django.utils import timezone


# Create your views here.**


@login_required(login_url="main:index")
def club(request):
    all_requests = Request.objects.all()
    today = timezone.now()
    todays_events = [request for request in all_requests if request.date.date() == today.date() and request.statut=='process']  
    Request.objects.filter(date__lte=today).delete()# __lte less than and equall
    clubs = User.objects.count()-1
    club_requests = Request.objects.filter(name=request.user).order_by('-date_request')
    accepted = Request.objects.filter(name=request.user, statut='process').count()
    denied = Request.objects.filter(name=request.user, statut='denied').count()
    awaits =  Request.objects.filter(name=request.user, statut='await')
    form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
    form.save()
    context ={
      'requests_list': club_requests ,
      'requests_not_await': club_requests.exclude(statut="await") ,
      'events_list': todays_events , 
      'today': today.strftime("%d %B , %Y"),
      'clubs': clubs ,
      'accepted': accepted,
      'denied' : denied,
      'awaits': awaits.count(), 
      'notification':'has-noti' if accepted>0 or denied>0  else '',
      'form':form,
    }
    return render(request, 'club/club.html', context)

@login_required(login_url="main:index")
def submit_event_view(request):
  if request.method=='POST':
    event = request.POST.get('event')
    classe = request.POST.get('classe')
    description = request.POST.get('description')
    date = request.POST.get('date')
    request = Request(name=request.user, event=event, classe=classe, description=description ,date=date)
    request.save()
    return  HttpResponseRedirect(reverse('club:club_portal',args=() ))
  return render(request, 'club/club_request.html',)
    


@login_required(login_url="main:index")
def form_view(request , pk):
  club_request = Request.objects.get(pk=pk)
  if club_request.name==request.user: 
    if not request.user.is_staff :
      accepted = Request.objects.filter(name=request.user, statut='process').count()
      denied = Request.objects.filter(name=request.user, statut='denied').count()#for the notifications
      club_requests = Request.objects.filter(name=request.user)#for notification
    
      context={
        'requests_not_await': club_requests.exclude(statut="await") ,
        'pk':club_request.pk,
        'club':club_request.name,
        'event' :club_request.event,
        'classe' : club_request.classe,
        'date' : club_request.date,
        'description' : club_request.description,
        'note': club_request.note if club_request.note != None else 'No Notes for you' ,
        'notification':'has-noti' if accepted>0 or denied>0  else '',
      }
      return render(request, 'club/view_form.html', context)
    else:
      return Http404()
  return  HttpResponseRedirect(reverse('club:club_portal',args=() ))

project/templates/club/club.html
{% extends 'layout.html' %}
{% block content %}

{% if not user.is_staff %}
<div class="row-m-t-20 row mt-3">
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="overview-wrap">
                        <h2 class="title-1">overview</h2>
                    </div>
                </div>
            </div>
            <div class="row m-t-25">
                <div class="col-sm-6 col-lg-3">
                    <div class="overview-item overview-item--c1">
                        <div class="overview__inner">
                            <div class="overview-box clearfix">
                                <div class="icon">
                                    <i class="zmdi zmdi-account-o"></i>
                                </div>
                                <div class="text">
                                    <h2>{{ clubs }}</h2>
                                    <span>Clubs</span>
                                </div>
                            </div>
                            <div class="overview-chart">
                                <canvas id="widgetChart1"></canvas>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-3">
                    <div class="overview-item overview-item--c2">
                        <div class="overview__inner">
                            <div class="overview-box clearfix">
                                <div class="icon">
                                    <i class="zmdi zmdi-thumb-up"></i>
                                </div>
                                <div class="text">
                                    <h2>{{ accepted }}</h2>
                                    <span>Accepted</span>
                                </div>
                            </div>
                            <div class="overview-chart">
                                <canvas id="widgetChart2"></canvas>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-3">
                    <div class="overview-item overview-item--c3">
                        <div class="overview__inner">
                            <div class="overview-box clearfix">
                                <div class="icon">
                                    <i class="zmdi zmdi-thumb-down"></i>
                                </div>
                                <div class="text">
                                    <h2>{{ denied }}</h2>
                                    <span>Denied</span>
                                </div>
                            </div>
                            <div class="overview-chart">
                                <canvas id="widgetChart3"></canvas>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-3">
                    <div class="overview-item overview-item--c4">
                        <div class="overview__inner">
                            <div class="overview-box clearfix">
                                <div class="icon">
                                    <i class="zmdi zmdi-calendar-note"></i>
                                </div>
                                <div class="text">
                                    <h2>{{ awaits }}</h2>
                                    <span>Awaits</span>
                                </div>
                            </div>
                            <div class="overview-chart">
                                <canvas id="widgetChart4"></canvas>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container-fluid">
                <div class="row ">
                    <div class="col-md-12">
                        <div class="overview-wrap">
                            <h2 class="title-1">Events list</h2>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row-m-t-25 row mt-3">
                <div class="col-md-12 ">
                    <!-- DATA TABLE-->
                    <div class="table-responsive m-b-40">
                        <table class="table table-borderless table-data3">
                            <thead>
                                <tr>
                                    <th>Date</th>
                                    <th>Club</th>
                                    <th>Event name</th>
                                    <th>Status</th>
                                    <th>class N*</th>
                                    <th>More</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for request in requests_list %}
                                <tr>
                                    <td>{{ request.date }}</td>
                                    <td><a
                                            href="{% url 'club:view' pk=request.pk %}">{{ request.name }}</a>
                                    </td>
                                    <td>{{ request.event }}</td>
                                    <td class="{{ request.statut }}  ">{{ request.get_statut_display }}</td>
                                    <td>{{ request.classe }}</td>

                                    <td>
                                        <div class="table-data-feature">
                                            <a class="item" data-toggle="tooltip" data-placement="top" title=""
                                                data-original-title="More" href="{% url 'club:view' pk=request.pk %}">
                                                <i class="zmdi zmdi-more" ></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="row justify-content-md-center">
            <div class="col-lg-6">
                <div class="au-card au-card--no-shadow au-card--no-pad">
                    <div class="au-card-title" style="background-image:url('/static/club/images/bg-title-01.jpg');">
                        <div class="bg-overlay bg-overlay--blue"></div>
                        <h3>
                            <i class="zmdi zmdi-account-calendar"></i>{{ today }}
                        </h3>

                        <a class="au-btn-plus" href="{% url 'club:submit_event' %}">
                            <i class="zmdi zmdi-plus"></i>
                        </a>

                    </div>
                    <div class="au-task ">
                        <div class="au-task__title">
                        {% if events_list %}    
                            <p>Events this day</p>
                        </div>
                        {% for event in events_list %}
                        <div class="au-task__item au-task__item--success">
                            <div class="au-task__item-inner">
                                <h5 class="task">
                                    <a>{{ event.event }}</a>
                                </h5>
                                <span class="time">
                                    <!-- time -->{{ event.date| time:"H:i" }} -- {{ event.classe }}</span>
                            </div>
                            {% endfor %}
                        {% else %}
                        <p>No events today</p>
                        </div>
                        {% endif %}



                            <!-- colors
                              au-task__item--primary
                              au-task__item--success
                              au-task__item--danger
                              au-task__item--warning
                            -->
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>
</div>
{% else %}
<div class="row-m-t-20 row mt-3">
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="row">
                <h1>You dont have permission !!</h1>
            </div>
        </div>
    </div>
</div>
{% endif %}

{% endblock %}

project/templates/club/club_request.html
{% extends 'layout.html' %}
{% block stylesheet %}


{% endblock %}
{% block content %} 
{% if not user.is_staff %}
<form action="{% url 'club:submit_event'   %}" method="POST">
    {% csrf_token %}
    <div class="row justify-content-md-center">
        <div class="col-lg-6">

            <div class="card">
                <div class="card-header">
                    <strong>Request </strong> Form
                </div>
                <div class="card-body card-block">
                    <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                        <div class="row form-group">
                            <div class="col col-md-3">
                                <label class=" form-control-label">Club</label>
                            </div>
                            <div class="col-12 col-md-9">
                                <p class="form-control-static" name="club" value="{{ user.username }}">{{ user.username }}</p>
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col col-md-3">
                                <label for="disabled-input" class=" form-control-label" >Event </label>
                            </div>
                            <div class="col-12 col-md-9">
                                <input type="text" id="disabled-input" name="event" placeholder="Event"
                                    class="form-control" required>
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col col-md-3">
                                <label for="disabled-input" class=" form-control-label">Date</label>
                            </div>
                            <div class="col-lg-6">
                                <input type="datetime-local" name="date" placeholder="Select Date time">
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col col-md-3">
                                <label for="disabled-input" class=" form-control-label">Classe</label>
                            </div>
                            <div class="col-12 col-md-9">
                                <input type="text" id="input" name="classe" placeholder="Classe example:BIB1 "
                                    class="form-control" required>
                            </div>
                        </div>

                        <div class="row form-group">
                            <div class="col col-md-3">
                                <label for="textarea" class=" form-control-label">Description</label>
                            </div>
                            <div class="col-12 col-md-9">
                                <textarea name="description" id="textarea-disabled-input" rows="9"
                                    placeholder="Description.." class="form-control" required></textarea>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-success btn-sm">
                                <i class="fa fa-dot-circle-o"></i> Send
                            </button>
                            <button type="reset" class="btn btn-danger btn-sm">
                                <i class="fa fa-ban"></i> Reset
                            </button>
                        </div>
                </div>

            </div>
</form>
{% else %}
<div class="row-m-t-20 row mt-3">
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="row">
                <h1>You dont have permission !!</h1>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}
{% block js %}

{% endblock %}

project/templates/club/view_form.html
{% extends 'layout.html' %}
{% block content %}
{% if not user.is_staff %}
<form action="{% url 'administration:submit_form' pk=pk  %}" method="POST">
    {% csrf_token %}
    <div class="row justify-content-md-center">
        <div class="col-lg-6">

            <div class="card">
                <div class="card-header">
                    <strong>Request </strong> Form
                </div>
                <div class="card-body card-block">
                    <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                        <div class="row form-group">
                            <div class="col col-md-3">
                                <label class=" form-control-label">Club</label>
                            </div>
                            <div class="col-12 col-md-9">
                                <p class="form-control-static">{{ club }}</p>
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col col-md-3">
                                <label for="disabled-input" class=" form-control-label">Event </label>
                            </div>
                            <div class="col-12 col-md-9">
                                <input type="text" id="disabled-input" name="disabled-input" placeholder="{{ event }}"
                                    disabled="" class="form-control">
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col col-md-3">
                                <label for="disabled-input" class=" form-control-label">Date</label>
                            </div>
                            <div class="col-12 col-md-9">
                                <input type="text" id="disabled-input" name="disabled-input" placeholder="{{date }}"
                                    disabled="" class="form-control">
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col col-md-3">
                                <label for="disabled-input" class=" form-control-label">Classe</label>
                            </div>
                            <div class="col-12 col-md-9">
                                <input type="text" id="disabled-input" name="disabled-input" placeholder="{{classe }}"
                                    disabled="" class="form-control">
                            </div>
                        </div>

                        <div class="row form-group">
                            <div class="col col-md-3">
                                <label for="textarea" class=" form-control-label">Description</label>
                            </div>
                            <div class="col-12 col-md-9">
                                <textarea name="textarea" id="textarea-disabled-input" rows="9"
                                    placeholder="{{ description }}" class="form-control" disabled=""></textarea>
                            </div>
                        </div>

                        <div class="row form-group">
                            <div class="col col-md-3">
                                <label for="textarea" class=" form-control-label">Note</label>
                            </div>
                            <div class="col-12 col-md-9">
                                <textarea name="note" id="textarea-disabled-input" rows="9" placeholder="{{ note }}"
                                    class="form-control" disabled=""></textarea>
                            </div>
                        </div>

                        
                </div>

            </div>
</form>
{% else %}
<div class="row-m-t-20 row mt-3">
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="row">
                <h1>You dont have permission !!</h1>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}