project/club/urls.py
from django.urls import path
from . import views


app_name = 'club'
urlpatterns = [
    path('', views.club, name='club_portal'),  # route for the club space
    path('form/', views.submit_event_view, name='submit_event'), # the submittion of the event request and route to form page
    path('form/<pk>', views.form_view, name='view')
]

project/main/urls.py
from django.urls import path
from . import views


app_name = 'main'
urlpatterns = [
    path('', views.index_view, name='index'), # route for the authentication page
    path('signup/', views.signup_view, name='signup'),#route for sign up page
    path('login/', views.login_view, name='login'), # route for login
    path('logout/', views.logout_view, name='logout'), # route for logout
]

project/project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Club/', include("club.urls")),
    path('Administration/', include('administration.urls')),
    path('main/', include('main.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='static\media\default.jpg', upload_to='static/media')

    def __str__(self):
        return f"{ self.user.username } profile"


@receiver(post_save, sender=User)
def update_profile_signal(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()#when a user signup this adds a profile automatically

project/main/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Profile


class RegisterForm(forms.ModelForm):
    username = forms.CharField(max_length=15,required=True, widget=forms.TextInput(
        attrs={'placeholder' : "Club Name"}
    ))
    email = forms.EmailField(required=True, widget=forms.EmailInput(
        attrs={'placeholder' : "Email"}
    ) )
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder' : "Password" , "id":"password", "name":"password"}
    ))
    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder' : "Re_Password", "id":"password1", "name":"password1"}
    ))

    class Meta:
        model = User
        fields = ("username",  "email", "password" ,)


    def clean_username(self, *args, **kwargs): # Validates the Username Field
        username = self.cleaned_data.get('username')
        queryset = User.objects.filter(username=username)
        if len(queryset)>0:
            raise forms.ValidationError(username + ' is already used')
        return username

    def clean_email(self, *args):
        email = self.cleaned_data.get('email')
        queryset = User.objects.filter(email=email)
        if len(queryset)>0:
            raise forms.ValidationError('email is already used')
        return email

    def clean_password1(self, *args):
        password = self.cleaned_data.get('password')
        password1 = self.cleaned_data.get('password1')
        if password and password1 and password==password1 :
            return password
        else:
            raise forms.ValidationError('password doesnt match')

class ProfileForm(forms.ModelForm):
    
    class Meta:
        model = Profile
        fields = ("image",)



      

project/main/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from main.forms import RegisterForm
from project.settings import EMAIL_HOST_USER
from django.core.mail import send_mail


def index_view(request):
  if request.user.is_authenticated: # we test if the user already authenticated
    if request.user.is_staff: # make redirection based on is_staff or not
      return HttpResponseRedirect(reverse('administration:admin_portal', args=()))
    elif not request.user.is_staff:
      return HttpResponseRedirect(reverse('club:club_portal', args=()))
  else: # if the user not authenticated, we must show him the login page
    return render(request, 'main/login.html')

def signup_view(request):
  if not request.user.is_authenticated:
    form = RegisterForm(request.POST or None)
    if form.is_valid():
      username = form.cleaned_data.get('username')
      password = form.cleaned_data.get('password')
      form.save()
      #subject = 'Welcome to ISIEVENT'
      #message = 'You created an account now '
      #recepient = str(form['email'].value())
      #send_mail(subject, message, EMAIL_HOST_USER, [recepient], fail_silently = False) for email verification
      user = User.objects.get(username=username)
      user.set_password(password)# because the form is making the password unusable for the authentification
      user.save()
      form = RegisterForm()
      return HttpResponseRedirect(reverse('main:index', args=()))
    return render(request, 'main/signup.html', {"form":form})
  return HttpResponseRedirect(reverse('main:index', args=()))


def login_view(request):
  username = request.POST.get('name', False)
  password = request.POST.get('pass', False)
  user = authenticate(username=username, password=password)   #autheticate
  if user is not None and user.is_active: # if the authetication goes well and the user is active
    login(request, user) # do the login in django system
    if user.is_staff:
      return HttpResponseRedirect(reverse('administration:admin_portal', args=()))
    elif not user.is_staff:
      return HttpResponseRedirect(reverse('club:club_portal', args=()))
  else:
    return render(request, 'main/login.html', { 'notexist':'Club doesnt exist or false password ' })

def logout_view(request):
  logout(request)
  return render(request, 'main/login.html')

project/templates/main/login.html
{% extends 'index.html' %}

{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static '/main/fonts/material-icon/css/material-design-iconic-font.min.css' %}">
<link rel="stylesheet" href="{% static '/main/css/style.css' %}">
<link rel="stylesheet" href="{% static '/main/css/cosmo.min.css' %}">
{% endblock %}


{% block content %}

<div class="main">
    <section class="sign-in">
        <div class="container">
            <div class="signin-content">
                <div class="signin-image">
                    <figure><img src="{% static '/main/images/signin-image.jpg' %}" alt="sing up image"></figure>
                    <a href="{% url 'main:signup' %}" class="signup-image-link">Create an account</a>
                </div>

                <div class="signin-form">
                    <h2 class="form-title">Sign In</h2>
                    <form method="POST" class="register-form" id="login-form" action="{% url 'main:login' %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="your_name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                            <input type="text" name="name" id="your_name" placeholder="Club Name" />
                        </div>
                        <div class="form-group">
                            <label for="your_pass"><i class="zmdi zmdi-lock"></i></label>
                            <input type="password" name="pass" id="your_pass" placeholder="Password" />
                        </div>
                        {% if notexist %}
                        <div class="top">
                            <div class="alert alert-dismissible alert-danger">
                                <strong>Error !</strong> <a href="{% url 'main:signup' %}"
                                    class="alert-link">{{ notexist }} click me to create an account!</a>
                            </div>
                        </div>
                        {% endif %}
                        <div class="form-group">
                            <input type="checkbox" name="remember-me" id="remember-me" class="agree-term" />
                            <label for="remember-me" class="label-agree-term"><span><span></span></span>Remember
                                me</label>
                        </div>
                        <div class="form-group form-button">
                            <input type="submit" name="signin" id="signin" class="form-submit" value="Log in" />
                        </div>
                    </form>
                    <div class="social-login">
                        <span class="social-label">Or login with</span>
                        <ul class="socials">
                            <li><a href="#"><i class="display-flex-center zmdi zmdi-facebook"></i></a></li>
                            <li><a href="#"><i class="display-flex-center zmdi zmdi-twitter"></i></a></li>
                            <li><a href="#"><i class="display-flex-center zmdi zmdi-google"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>

</div>

{% endblock %}

{% block js %}
<script src="{% static '/main/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static '/main/js/main.js' %}"></script>
{% endblock %}

project/templates/main/signup.html
{% extends 'index.html' %}
{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static '/main/fonts/material-icon/css/material-design-iconic-font.min.css' %}">    
    <link rel="stylesheet" href="{% static '/main/css/style.css' %}">
    <link rel="stylesheet" href="{% static '/main/css/cosmo.min.css' %}">
{% endblock %}

{% block content %}
    {% if exist %}
     <div class="top" >
        <div class="alert alert-dismissible alert-danger">
            <strong>Error !</strong> <a href="{% url 'main:index' %}" class="alert-link">{{ exist }} click me</a> 
        </div>
    </div>
        {% endif %}
    <div class='main'>
        <section class="signup">
            <div class="container">
                <div class="signup-content">
                    <div class="signup-form">
                        <h2 class="form-title">Sign up</h2>
                        <form method="POST" class="register-form" id="register-form" action="{% url 'main:signup' %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                {{ form.username }} 
                                
                            </div>
                            {% if form.username.errors %}
                            <div class="alert alert-danger">
                                <strong>{{ form.username.errors }}</strong> 
                            </div> 
                                {% endif %}
                            <div class="form-group">
                                <label for="email"><i class="zmdi zmdi-email"></i></label>
                                {{ form.email }}
                            </div>
                            {% if form.email.errors %}
                            <div class="alert alert-danger">
                                <strong>{{ form.email.errors }}</strong> 
                            </div> 
                                {% endif %}
                            <div class="form-group">
                                <label for="pass"><i class="zmdi zmdi-lock"></i></label>
                                {{ form.password }}
                            </div>
                           
                            <div class="form-group">
                                <label for="re-pass"><i class="zmdi zmdi-lock-outline"></i></label>
                                {{ form.password1 }}
                            </div>
                            {% if form.password1.errors %}
                            <div class="alert alert-danger">
                                <strong>{{ form.password1.errors }}</strong> 
                            </div> 
                                {% endif %}<span id='message'></span>
                            <div class="form-group">
                                <input type="checkbox" name="agree-term" id="agree-term" class="agree-term" />
                                <label for="agree-term" class="label-agree-term" required><span><span></span></span>I agree all statements in  <a href="#" class="term-service" required>Terms of service</a></label>
                            </div>
                            <div class="form-group form-button">
                                <input type="submit" name="signup" id="signup" class="form-submit" value="Register"/>
                            </div>
                        </form>
                    </div>
                    <div class="signup-image">
                        <figure><img src="{% static '/main/images/signup-image.jpg' %}" alt="sing up image"></figure>
                        <a href="{% url 'main:index' %}" class="signup-image-link">I am already member</a>
                    </div>
                </div>
            </div>
        </section>
    </div>

{% endblock %}
    
{% block js %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="{% static '/main/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static '/main/js/main.js' %}"></script>
    <script >
    $('#password, #password1').on('keyup', function () {
        if ($('#password').val() == $('#password1').val()) {
          $('#message').html('Matching').css('color', 'green');
        } else 
          $('#message').html('Not Matching').css('color', 'red');
      });
    </script>
{% endblock %}